# Site settings
email: minhdao@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: minh's notes
description: where my thoughts are
url: ""
twitter_username:
default_img:

# Profile settings
name: Minh Dao
profile_img: ./assets/pics/me.jpg
profile: Minh is into web development and crypto currency. Living in Ho Chi Minh City, Viet Nam. All time learner and player :)
social:
  github: https://github.com/minhdao
  linkedin: https://www.linkedin.com/in/minh-dao-b635a056/
  instagram: https://www.instagram.com/minhdao6/

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
