title: Minh's notes
description: Personal notes about tech topics and more. Also great if these notes can help anyone in one way or the other :)

url: https://minhdao.github.io
resume: https://drive.google.com/file/d/1QukRJ_vZFMe7CfE-IBdCzn2Xdu1ZPXoo/view?usp=sharing
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: about
      url: /about
    - title: notes
      url: /index.html
    - title: contact
      url: /contact

social:
    github: minhdao
    email: minhdao6@gmail.com
    linkedin: minh-dao-b635a056

google_analytics: "UA-58263416-1"

disqus:
    shortname: mdao
